name: Update README2

on:
  schedule:
    - cron: "0 */12 * * *"   # cada 12 horas (medianoche y mediodía UTC)
  workflow_dispatch:

permissions:
  contents: write   # 👈 necesario para que el bot pueda commitear/pushear

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README

    steps:
      - uses: actions/checkout@v4.2.2

      - uses: Readme-Workflows/recent-activity@v2.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
